# Generated by Django 4.0.3 on 2024-02-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('litr', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'User')], default=3),
        ),
        migrations.CreateModel(
            name='ProductOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_products', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.producttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_products', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.producttemplate')),
            ],
        ),
    ]
