# Generated by Django 4.0.3 on 2024-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_promotion_alter_productoutcome_selling_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoutcome',
            old_name='selling_price',
            new_name='sold_price',
        ),
        migrations.AlterField(
            model_name='productincome',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
