# Generated by Django 4.0.3 on 2024-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_rename_selling_price_productoutcome_sold_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincome',
            old_name='product',
            new_name='product_template',
        ),
        migrations.RenameField(
            model_name='productoutcome',
            old_name='product',
            new_name='product_template',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='product',
            new_name='product_template',
        ),
        migrations.RemoveField(
            model_name='producttemplate',
            name='litr',
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='volume_liters',
            field=models.IntegerField(default=1, verbose_name='Hajmi(Litrda): '),
            preserve_default=False,
        ),
    ]
