# Generated by Django 4.0.3 on 2024-02-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_rename_product_productincome_product_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='productincome',
            name='number_of_products',
            field=models.IntegerField(verbose_name='Sotib olingan maxsulot soni'),
        ),
        migrations.AlterField(
            model_name='productincome',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maxsulotning sotib olingan narxi'),
        ),
        migrations.AlterField(
            model_name='productincome',
            name='product_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.producttemplate', verbose_name='Maxsulot nomi'),
        ),
        migrations.AlterField(
            model_name='productoutcome',
            name='number_of_products',
            field=models.IntegerField(verbose_name='Number of Products'),
        ),
        migrations.AlterField(
            model_name='productoutcome',
            name='product_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.producttemplate', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productoutcome',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sold Price'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Maxsulot nomi'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.account')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.account')),
            ],
        ),
        migrations.AddField(
            model_name='productincome',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.account', verbose_name='Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoutcome',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.account', verbose_name='Account'),
            preserve_default=False,
        ),
    ]
