# Generated by Django 4.0.3 on 2024-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_account_alter_productincome_number_of_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'User')]),
        ),
    ]
