# Generated by Django 4.0.3 on 2024-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Mavjud Summa'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xisob raqam'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Naqd'), (2, 'Karta'), (3, 'Qarz')], verbose_name='Xisob raqam turi'),
        ),
    ]
