# Generated by Django 4.0.3 on 2024-02-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_alter_account_balance_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
