# Generated by Django 4.0.3 on 2024-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_telegramuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='latitude',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='longitude',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(default='', max_length=250),
        ),
    ]
