# Generated by Django 4.0.3 on 2024-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_telegramuser_full_name_telegramuser_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Sotib olish narxi:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Sotish narxi:'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductOutcome',
        ),
    ]
