# Generated by Django 4.0.3 on 2024-02-21 09:13

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_producttemplate_buying_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Sotib olish'), (2, 'Sotish')], default=1)),
                ('number_of_products', models.IntegerField(verbose_name='Sotib olingan maxsulot soni')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Naqd'), (2, 'Karta'), (3, 'Qarz'), (4, "O'tkazma")], verbose_name='Xisob raqam turi'),
        ),
        migrations.DeleteModel(
            name='ProductIncome',
        ),
        migrations.AddField(
            model_name='productinout',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='productinout',
            name='product_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.producttemplate', verbose_name='Maxsulot nomi'),
        ),
    ]
