# Generated by Django 4.0.3 on 2024-02-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_productinout_alter_account_type_delete_productincome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField(verbose_name='Buyurtma qilingan maxsulotlar')),
                ('status', models.IntegerField(choices=[(1, 'Aktiv buyurtma'), (2, 'Bajarildi'), (3, 'Bekor qilindi')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.telegramuser', verbose_name='Klient')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.producttemplate')),
            ],
        ),
    ]
