# Generated by Django 4.0.3 on 2024-02-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Kirim'), (2, 'Chiqim')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='account',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
