# Generated by Django 4.0.3 on 2024-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_inoutcome_remove_outcome_account_delete_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='longitude',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2),
        ),
    ]
