# Generated by Django 4.0.3 on 2024-02-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_remove_telegramuser_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.subscription'),
        ),
    ]
