# Generated by Django 4.0.3 on 2024-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0017_telegramuser_is_active_telegramuser_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Karta orqali'), (2, 'Naqd orqali')], default=0),
        ),
    ]
