# Generated by Django 4.0.3 on 2024-02-22 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0018_alter_telegramuser_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='expires_after',
            field=models.IntegerField(default=1, verbose_name="Necha kundan so'ng tarif passiv bo'ladi?"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tgbot.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='tgbot.telegramuser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tgbot.telegramuser')),
            ],
        ),
    ]
