# Generated by Django 4.0.3 on 2024-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_remove_telegramuser_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
