# Generated by Django 4.0.3 on 2024-02-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_alter_usersubscription_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='bonus_balance',
            field=models.IntegerField(default=0),
        ),
    ]
