# Generated by Django 4.0.3 on 2024-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0021_telegramuser_bonus_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='number_of_available_products',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
