# Generated by Django 4.0.3 on 2024-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0022_usersubscription_number_of_available_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='number_of_available_products',
            field=models.IntegerField(default=0),
        ),
    ]
