# Generated by Django 4.0.3 on 2024-03-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0024_order_curier_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutcome',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.account', verbose_name='Xisob'),
        ),
        migrations.AlterField(
            model_name='inoutcome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='inoutcome',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='inoutcome',
            name='status',
            field=models.IntegerField(choices=[(1, 'Kirim'), (2, 'Chiqim')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='bonus',
            field=models.IntegerField(verbose_name="Qo'shiladigan bonus bali"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotilish narxi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product_count',
            field=models.IntegerField(verbose_name='Maxsulot soni'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.producttemplate', verbose_name='Maxsulot'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Foydalanuvchi'), (3, 'Kurier')], default=2, verbose_name='Rol'),
        ),
    ]
