# Generated by Django 4.0.3 on 2024-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0025_alter_inoutcome_account_alter_inoutcome_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='payment_status',
            field=models.IntegerField(choices=[(1, "To'lov qilmadi"), (2, "To'lov kutilmoqda"), (3, "To'lov qilindi")], default=1, verbose_name="To'lov statusi"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tarif Nomi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Foydalanuvchi')], default=2, verbose_name='Rol'),
        ),
    ]
