# Generated by Django 4.0.3 on 2024-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0026_telegramuser_payment_status_alter_subscription_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('chat_id', models.CharField(max_length=255, verbose_name='Chat ID')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('passport_data', models.CharField(max_length=255, verbose_name="Passport ma'lumotlari")),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone_numbers_2', models.CharField(max_length=255, verbose_name='2 chi telefon raqami')),
                ('car_model', models.CharField(max_length=255, verbose_name='Mashina modeli')),
                ('car_license_plate', models.CharField(max_length=255, verbose_name='Mashina davlat raqami')),
            ],
        ),
    ]
