# Generated by Django 4.0.3 on 2024-03-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0028_referral_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tgbot.telegramuser', verbose_name='Klient'),
        ),
    ]
