# Generated by Django 4.0.3 on 2024-03-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0030_alter_curier_address_alter_curier_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='curier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='tgbot.curier', verbose_name='Kurier'),
        ),
    ]
