# Generated by Django 4.0.3 on 2024-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0031_alter_order_curier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_status',
            field=models.IntegerField(choices=[(1, "To'lov qilmadi"), (2, "To'lov kutilmoqda"), (3, "To'lov qilindi")], default=1, verbose_name="To'lov statusi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aktiv buyurtma'), (2, 'Bajarildi'), (3, 'Bekor qilindi'), (4, "Buyurtma yo'lda")], default=1),
        ),
    ]
