# Generated by Django 4.0.3 on 2024-03-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0032_remove_telegramuser_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Foydalanuvchi Tarifi', 'verbose_name_plural': 'Foydalanuvchi Tariflari'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(verbose_name='Mavjud Summa'),
        ),
        migrations.AlterField(
            model_name='inoutcome',
            name='amount',
            field=models.IntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='buying_price',
            field=models.IntegerField(verbose_name='Sotib olish narxi:'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='selling_price',
            field=models.IntegerField(verbose_name='Sotish narxi:'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='number_of_stars',
            field=models.IntegerField(verbose_name='Bonus ballar'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.IntegerField(verbose_name='Sotilish narxi'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.subscription', verbose_name='Tarif'),
        ),
    ]
