# Generated by Django 4.0.3 on 2024-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0033_alter_usersubscription_options_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscription_based',
            field=models.BooleanField(default=True),
        ),
    ]
