# Generated by Django 4.0.3 on 2024-04-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0034_telegramuser_subscription_based'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='subscription_based',
            field=models.BooleanField(default=True, verbose_name="Tarif bo'yicha sotib oladimi?"),
        ),
        migrations.CreateModel(
            name='BonusExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField()),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
