# Generated by Django 4.0.3 on 2024-06-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0035_alter_telegramuser_subscription_based_bonusexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutcome',
            name='status',
        ),
        migrations.AddField(
            model_name='inoutcome',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.telegramuser'),
            preserve_default=False,
        ),
    ]
