# Generated by Django 4.0.3 on 2024-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0037_alter_telegramuser_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutcome',
            name='status',
            field=models.CharField(choices=[(1, 'Kirim'), (2, 'Chiqim')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
