# Generated by Django 4.0.3 on 2024-06-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0038_inoutcome_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='curier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='tgbot.curier', verbose_name='Kurier'),
        ),
    ]
