# Generated by Django 4.0.3 on 2024-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0041_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(verbose_name='created_date'),
        ),
    ]
