# Generated by Django 4.0.3 on 2024-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0042_alter_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='cashback',
            field=models.BigIntegerField(default=0, verbose_name='Kashbak summasi'),
        ),
    ]
