# Generated by Django 4.0.3 on 2024-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0043_telegramuser_cashback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tariflar'},
        ),
        migrations.AddField(
            model_name='order',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
