# Generated by Django 4.0.3 on 2024-06-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0045_alter_order_created_at_alter_order_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='available_bottles',
            field=models.IntegerField(default=1, verbose_name="Bo'sh idishlar soni"),
            preserve_default=False,
        ),
    ]
