# Generated by Django 4.0.3 on 2024-07-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0048_remove_subscription_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referal_bonus',
            field=models.IntegerField(default=0, verbose_name="Referal bonusi (so'mda)"),
        ),
    ]
