# Generated by Django 4.0.3 on 2024-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0049_subscription_referal_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='bonus_balance',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bonus_in_percent',
            field=models.IntegerField(default=0, verbose_name='Tarif sotib olish uchun bonus foizi'),
        ),
    ]
